### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by LucaMarconato** [ADJA/algos#2]
First, congratulation for your work, it is incredible 🥇 

Is your code free to be refused, what are the terms? I do not see any license.
If it is free code, please add a license, in fact in some countries the absence of a license does not mean that people can freely use it, as it is stated here.

https://www.gnu.org/licenses/license-list.html#NoLicense

Thank you.

**Comment by ADJA** [comment]
Hi, thanks! :)

Good point. Just added MIT license,  feel free to use the code as you want!
